### PR TITLE
Bye bye node-sass, welcome Dart Sass

### LINKED ISSUE #49: node-sass deprecated
> Warning: LibSass and Node Sass are deprecated. While they will continue to receive maintenance releases indefinitely, there are no plans to add additional features or compatibility with any new CSS or Sass features. Projects that still use it should move onto Dart Sass.

https://www.npmjs.com/package/node-sass

The mentioned dart-sass package is the npm `sass` package:
https://www.npmjs.com/package/sass

### PR DESCRIPTION
**Pull request by skjnldsv**
- removed node-sass
- installed sass
- copied the devDeps as peerDeps and update the package.json according to the lockfile (as the versions matched, the dependencies pr were updating the lockfile only)
- 
fix #49

### CODE REVIEW

**Comment by skjnldsv** [comment]
Will be a major as one of the peers deps changed.
The process is as easy as  

```
npm rm node-sass
npm i @nextcloud/webpack-vue-config@latest sass --also=dev
```

**Comment by skjnldsv** [comment]
Tested. Works

**Comment by jotoeri** [comment]
> Will be a major
Wanna do the webpack-move then, too? 😉 🙈 

> npm i --also=dev @nextcloud/webpack-vue-config@latest sass
This installed sass for me as dependency instead of devDependency...

**Review by jotoeri — APPROVED** [review]

**Comment by skjnldsv** [comment]
> This installed sass for me as dependency instead of devDependency...

I guess you're on an old npm?

**Comment by jotoeri** [comment]
> I guess you're on an old npm?

more or less, yes... `6.14.11`

**Comment by skjnldsv** [comment]
I dunno, I did `npm --dev`, and it told me it was deprecated :thinking:

**Review by blizzz — APPROVED** [review]

**Comment by jotoeri** [comment]
> I dunno, I did `npm --dev`, and it told me it was deprecated 🤔

Yeah, i think `--save-dev`is the trick nowadays...

**Pull request merged**
