### PR TITLE
Bump webpack-cli from ^3.3.12 to ^4.5.0

### PR DESCRIPTION
**Pull request by skjnldsv**
Signed-off-by: John Molakvoæ (skjnldsv) <skjnldsv@protonmail.com>

### CODE REVIEW

**Review by korelstar — COMMENTED** [review]
Sorry, but where is `webpack-cli` used? Building is done with the binary `webpack` which is in the `webpack` package. Therefore, we could remove this dependency. And even if a single app wants to use `webpack-cli` for this, the app could add the dependency manually. Am I wrong?

**Comment by skjnldsv** [comment]
Hum, that's a good point, is that actually needed?

**Comment by jotoeri** [comment]
Will need some adjustments probably, but after removing `--hide-modules` build runs through...

grafik

**Comment by skjnldsv** [comment]
I'M BACK :grin:

**Comment by skjnldsv** [comment]
> Will need some adjustments probably, but after removing `--hide-modules` build runs through on forms

Yes, weirdly, we already removed it on the latests apps releases. :shrug: 
https://github.com/nextcloud/contacts/commit/4f78ff403cec9466be00ea2a91a7b0cf2fde4d6e

We should have released this alongside 3.0.0, I don't wanna do another major lol

**Review by jotoeri — COMMENTED** [review]
> We should have released this alongside 3.0.0

As mentioned on the other PR - maybe include webpack 5, then too for `4.0.0`?

**Review by jotoeri — APPROVED** [review]

**Pull request merged**
