### PR TITLE
Use Asset Modules plus upgrade to npm 7

### PR DESCRIPTION
**Pull request by Pytal**
Use Asset Modules introduced in webpack 5 and upgrade to npm 7

Docs https://webpack.js.org/guides/asset-modules/

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Nice!!

**Comment by raimund-schluessler** [comment]
Do we need to specify the engines in `package.json` now that we use `"lockfileVersion": 2,`?

```

	"engines": {
		"node": ">=14.0.0",
		"npm": ">=7.0.0"
	},
```

**Comment by skjnldsv** [comment]
Would be nice @raimund-schluessler :rocket:

**Comment by Pytal** [comment]
> Do we need to specify the engines in `package.json` now that we use `"lockfileVersion": 2,`?

It's backwards compatible but I've added it for consistency across the nextcloud ecosystem :)

**Comment by artonge** [comment]
@Pytal @skjnldsv should we merge this ?

**Pull request merged**
