### PR TITLE
add loader for static files

### PR DESCRIPTION
**Pull request by korelstar**
In order to use Toasts from `@nextcloud/dialogs` you need to add `url-loader` for (at least) SVG files when importing the required style sheet. Therefore, I think this configuration should be part of the common webpack configuration. Otherwise, apps using those toasts have to add the complicated `webpack-merge` approach.

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]

**Comment by skjnldsv** [comment]
Good call!
Care to release?

**Comment by korelstar** [comment]
> Good call!
> Care to release?

Would like to see this released soon. Will create a PR for release since I have no access to master.

**Comment by skjnldsv** [comment]
> Would like to see this released soon. Will create a PR for release since I have no access to master.

done :heart:

**Comment by korelstar** [comment]
Thanks! (praying that I'm not doing anything wrong)

**Pull request merged**
