### PR TITLE
Do not polyfill available in a web browser Node modules

### PR DESCRIPTION
**Pull request by ShGKme**
See details in https://github.com/nextcloud/nextcloud-vue/issues/3864#issuecomment-1509437470

(requires more tests)

### CODE REVIEW

**Review by skjnldsv — APPROVED** [review]
Holly molly!! Good catch! :pray:

**Comment by ShGKme** [comment]
Tested in some apps, seems to work.

**Comment by skjnldsv** [comment]
Is it a breaking? Shall we wait for #450 before releasing `6.x.x` ?

**Comment by ShGKme** [comment]
> Is it a breaking?

I'm sure for 95% that it isn't. But remaining 5% wonder why Webpack ever had to polyfill `console` object and what it might break 😅

So, I'd say "let's wait a bug report 😅

**Pull request merged**
